project:
  type: website
  output-dir: _site

website:
  favicon: images/favicon.png
  title: "Turing PPL - Probabilistic Programming Languages"
  navbar:
    title: "Turing PPL"
    logo: images/favicon.png
    tools:
      - icon: github
        href: https://github.com/TuringPPL/TuringPPL.github.io
    right:
      - href: index.qmd
        text: Home
      - pages/Mission.qmd
      - pages/Team.qmd
      - pages/Resources.qmd
      - text: "Annual Meetings"
        href: pages/Annual_Meetings/index.qmd
      - text: "Forecasting Competitions"
        href: pages/Forecasting_Competitions/index.qmd
      - pages/get_involved.qmd 
  
  sidebar:
    - title: "Forecasting Competitions"
      style: "docked"
      background: light
      contents: 
        - pages/Forecasting_Competitions/index.qmd
        - pages/Forecasting_Competitions/Example.qmd
        - pages/Forecasting_Competitions/Winter_2024.qmd

        
    - title: "Annual Meetings"
      style: "docked"
      background: light
      contents: 
        - pages/Annual_Meetings/index.qmd
        - pages/Annual_Meetings/AM_2024.qmd
        
  page-footer:
    border: true
    left: Copyright 2024 - Turing PPL
    right:
      - text: "Probabilistic Programming Languages @ Turing"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    page-layout: full
