project:
  type: website
  output-dir: docs

website:
  favicon: images/favicon.png
  title: "Turing PPL"
  navbar:
    title: "Turing PPL"
    logo: images/favicon.png
    tools:
      - icon: github
        href: https://github.com/TuringPPL
    right:
      - href: index.qmd
        text: Home
      - Team.qmd
      - text: "Annual Meetings"
        href: Annual_Meetings/index.qmd
      - text: "Forecasting Competitions"
        href: Forecasting_Competitions/index.qmd
      - get_involved.qmd 
  
  sidebar:
    - title: "Forecasting Competitions"
      style: "docked"
      background: light
      contents: 
        - Forecasting_Competitions/index.qmd
        - Forecasting_Competitions/Example.qmd
        - Forecasting_Competitions/Winter_2024.qmd

        
    - title: "Annual Meetings"
      style: "docked"
      background: light
      contents: 
        - Annual_Meetings/index.qmd
        - Annual_Meetings/AM_2024.qmd
        
  page-footer:
    border: true
    left: Copyright 2024 - Turing PPL
    right:
      - text: "Probabilistic Programming Languages @ Turing"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    page-layout: full
