project:
  type: website
  output-dir: docs

website:
  bread-crumbs: true
  favicon: Logos/Logo_NoText.png
  title: "SPHERE-PPL"
  navbar:
    title: "SPHERE-PPL"
    logo: Logos/Logo_NoText.png
    tools:
      - icon: github
        href: https://github.com/SPHERE-PPL/SPHERE-PPL.github.io
    right:
      - href: index.qmd
        text: Home
      - pages/Mission.qmd
      - pages/Team.qmd
      - pages/Resources.qmd
      - text: "Events"
        href: pages/Events/index.qmd
      - text: "Forecasting Contests"
        href: pages/Forecasting_Contests/index.qmd
      - pages/get_involved.qmd 
  
  sidebar:
    - title: "Forecasting Contests"
      style: "floating"
      background: white
      
      contents: 
        - pages/Forecasting_Contests/index.qmd
        - pages/Forecasting_Contests/mpox_example.qmd
        - pages/Forecasting_Contests/Winter_2024.qmd

        
    - title: "Events"
      style: "floating"
      background: white
      contents: 
        - pages/Events/index.qmd
        - pages/Events/Jan25.qmd
        
  page-footer:
    border: true
    left: Copyright 2024 - SPHERE-PPL
    right:
      - text: "Spatial, Health & Environmental Research using Probilistic Programming Languages"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    page-layout: full
