---
title: "Get Involved"
---

# Join the Zulip

Zulip is a messaging and community platform that we will be using to host all Probabilistic Programming discussions. [You can sign-up here to join!](https://sphereppl.zulipchat.com/join/olwtpi7g3wbyh5mxv4uwipaw/) More information about zulip can be found on their website: <https://zulip.com/>

# Join the Mailing List

Every year, there will be workshops, meetings and forecasting challenges designed to further the use of Probabilistic Programming across research, industry and policy.

To be kept up-to-date with all the latest news and events, consider signing up to our mailing list using the form below. Details entered here will only be used for our mailing list and no other community platforms. If you would like to be removed from the mailing list, please email [info\@sphere-ppl.org](mailto:info@sphere-ppl.org).

<iframe width="100%" height="1000" src="https://forms.cloud.microsoft/Pages/DesignPageV2.aspx?origin=NeoPortalPage&subpage=design&id=B3WJK4zudUWDC0-CZ8PTB-r4zC9J81VJtk2cCebnWjZUMzMwMUxNUjlUNFgxWTlTMUlKU1pJSFI2Ny4u" frameborder="0" marginwidth="0" marginheight="0" style="border: none; max-width:100%; max-height:100%" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen>

</iframe>
